"""Add doctor_id to Note with named constraint

Revision ID: 4cb36a14766f
Revises: ee7670abeddd
Create Date: 2025-08-20 10:09:49.250876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb36a14766f'
down_revision = 'ee7670abeddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_note_doctor_id', 'doctor', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('fk_note_doctor_id', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
