"""Add doctor_id to Patient

Revision ID: ee7670abeddd
Revises: b9cb80aff892
Create Date: 2025-08-20 09:54:46.563988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7670abeddd'
down_revision = 'b9cb80aff892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_patient_doctor', 'doctor', ['doctor_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! 
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_doctor', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
